config/routes.rb
Enzify::Application.routes.draw do
  post '/products/:id/create-property', :to => 'properties#create'

  put '/opinion/:id', :to => 'opinions#vote'
  post '/opinion/:property', :to => 'opinions#create'
  delete '/opinion/:id', :to => 'opinions#delete'
  resources :products, :only => [:index, :show, :create, :update, :destroy]

  delete '/products/:id/create-property', :to => 'properties#delete'
  root :to => 'products#index'
  get "site/test" => 'site#test'
  post '/users/new-password', :to => 'users#new_password', :as => :new_password
  get '/users/me', :to => 'users#me', :as => :me
  get "/terms" => 'site#index'
  get "tmpl/:partial" => 'site#partials'
  match 'auth/:provider/callback' => 'authentications#create'
  devise_for :users

  get '/freescore', :to => 'site#freescore'

  get '/search/:terms', :to => 'products#search'

  resources :authentications, :only => [:index, :destroy, :create]

end

app/views/layouts/_footer.html.erb
<footer>
	<div class='center-content only-desktop'>
		<div>
			<h1>Contact us</h1>
			<p>For productors: <br />
			<%= link_to "productors@enzify.com", 'mailto:productors@enzify.com' %></p>
			<p>For markets, supermarkets or shops:<br />
			<%= link_to "implementation@enzify.com", 'mailto:implementation@enzify.com' %></p>
			<p>For the general public:<br />
			<%= link_to "contact@enzify.com", 'mailto:contact@enzify.com' %></p>
		</div>
		<div>
			<h1>Hello, world</h1>
			<p>bla bla bla</p>
			<p>Lorem ipsum sit amet</p>
			<p>Scan and discover</p>
			<p>&copy; 2012 Enzify</p>
		</div>
		<div>
			<h1>Useful links</h1>
			<p><a href='/terms'>Terms and conditions</a></p>
			<p>API for developers</p>
			<p>Mobile applications</p>
		</div>
	</div>
	<div class='center-content only-mobile' style='text-align:center'>
		&copy;2012 Enzify. <a href='/terms'>Terms</a>
	</div>
</footer>

app/views/layouts/_footer.ro.html.erb
<footer>
	<div class='center-content only-desktop'>
		<div>
			<h1>Contactați-ne</h1>
			<p>Pentru producători: <br />
			<%= link_to "productors@enzify.com", 'mailto:productors@enzify.com' %></p>
			<p>Pentru magazine:<br />
			<%= link_to "implementation@enzify.com", 'mailto:implementation@enzify.com' %></p>
			<p>Generalități:<br />
			<%= link_to "contact@enzify.com", 'mailto:contact@enzify.com' %></p>
		</div>
		<div>
			<h1>Bună, lume!</h1>
			<p>bla bla bla</p>
			<p>Lorem ipsum sit amet</p>
			<p>Scanează și descoperă</p>
			<p>&copy; 2012 Enzify</p>
		</div>
		<div>
			<h1>Legături utile</h1>
			<p><a href='/terms'>Termeni și condiții</a></p>
			<p>API for developers</p>
			<p>Mobile applications</p>
		</div>
	</div>
	<div class='center-content only-mobile' style='text-align:center'>
		&copy;2012 Enzify. <a href='/terms'>Termeni</a>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class='center-content' style='height:100%'>
		<div id='logo'><%= link_to "Enzify", '/' %></div>
		<div class='only-mobile' id='expend-menu'>
			<a href='javascript:void(0);' onclick='ui.toggleMenu();'><span></span></a>
		</div>
		<div class='only-mobile' style='clear:both'>
			<nav id='mobile-usermenu' style='display:none'>
				<% if current_user %>
					<%= link_to current_user.display_name, me_path %>
					<%=link_to I18n.t('layout.usermenu.authentications'), authentications_path %>
					<%=link_to I18n.t('layout.usermenu.my_account'), edit_user_registration_path %>
					<%=link_to I18n.t('layout.usermenu.sign_out'), destroy_user_session_path, :method => :delete %>
				<% else %>
					<%= link_to I18n.t('layout.usermenu.sign_in'), new_user_session_path %>
					<a href='/auth/twitter'>Twitter</a>
					<a href='/auth/facebook'>Facebook</a>
					<a href='/auth/google'>Google</a>
				<% end %>
			</nav>
		</div>
		<div id='search' class='only-desktop'>
			<input type='search' placeholder='<%= I18n.t 'layout.search_placeholder' %>' id='searchbox' />
		</div>
		<nav id='usermenu' class='only-desktop'>
			<% if current_user %>
				<%= link_to current_user.display_name, me_path %>
				<div>
					<ul>
						<li><%=link_to I18n.t('layout.usermenu.authentications'), authentications_path %></li>
						<li><%=link_to I18n.t('layout.usermenu.my_account'), edit_user_registration_path %></li>
						<li><%=link_to I18n.t('layout.usermenu.sign_out'), destroy_user_session_path, :method => :delete %></li>
					</ul>
				</div>
			<% else %>
				<%= link_to I18n.t('layout.usermenu.sign_in'), new_user_session_path %>
				<div>
					<ul>
						<li><a href='/auth/twitter'>Twitter</a></li>
						<li><a href='/auth/facebook'>Facebook</a></li>
						<li><a href='/auth/google'>Google</a></li>
					</ul>
				</div>
			<% end %>
		</nav>
	</div>
</header>

app/views/layouts/angular.html.erb
<!DOCTYPE html>
<html ng-app='enzify'>
<head>
  <title>Enzify</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='wrapper'>
	<%= render 'layouts/header' %>
	<div class='main-container'>
		<div class='center-content'>
			<% if notice %>
				<p class='notice'><%= notice %></p>
			<% end %>
			<% if alert %>
				<p class='alert'><%= alert %></p>
			<% end %>
			<div ng-view></div>
		</div>
	</div>
	<div id='push'></div>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enzify</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class='main-container'>
	<div class='center-content'>
		<% if notice %>
			<p class='notice'><%= notice %></p>
		<% end %>
		<% if alert %>
			<p class='alert'><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
</div>

<%= render 'layouts/footer' %>

</body>
</html>